apiVersion: apps/v1
kind: Deployment

metadata:
  name: nginx-deployment
spec:
  selector:
    matchLabels:
       app: nginx


  replicas: 3 # template to use  its label for k8
  template:
    metadata:
      labels:
        app: nginx


    spec:
    containers:
      - name: nginx
        image: meghanasrividya/my-page
        ports:
        - containerPort: 80
